{% set name = "pyMCR" %}
{% set version = "0.3.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2192520584d25ee74c9d466e9d9f3f806ca76ff00c0d85cbf6f1fc6932ebe0f8

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3
    - pytest-runner
  run:
    - numpy
    - python >=3
    - scipy
    - scikit-learn >=0.20

test:
  imports:
    - pymcr
    - pymcr.tests
  requires:
    - pytest
  commands:
    - pytest --pyargs pymcr


about:
  home: https://github.com/usnistgov/pyMCR
  license: NIST
  license_family: PUBLIC-DOMAIN
  license_file: LICENSE.md
  summary: Multivariate Curve Resolution in Python
  doc_url: https://pages.nist.gov/pyMCR
  dev_url: https://github.com/usnistgov/pyMCR

extra:
  recipe-maintainers:
    - CCampJr
    - ericpre
