{% set name = "pyMCR" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cefa25c5cc788e466c074aa562baf9f0a91f73bf7d37b04ca82ff2604cc3bf2e

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3
    - pytest-runner
  run:
    - numpy
    - python >=3
    - scipy
    - scikit-learn >=0.20

test:
  imports:
    - pymcr
    - pymcr.tests
  requires:
    - pytest
  commands:
    - pytest --pyargs pymcr


about:
  home: https://github.com/usnistgov/pyMCR
  license: NIST-PD-fallback
  license_file: LICENSE.md
  summary: Multivariate Curve Resolution in Python
  doc_url: https://pages.nist.gov/pyMCR
  dev_url: https://github.com/usnistgov/pyMCR

extra:
  recipe-maintainers:
    - CCampJr
    - ericpre
