travis:
  secure:
    BINSTAR_TOKEN: KxdBoQJa8A8273SAS8uKVArSGxTVLyPThaWGthTIlnE+xshIgXXy/hND6INNJgCPrWlatutjN1s9K6F/qLTUPFVaXnUcIIO9KGX/Xd9pJRNNnVB72zIiMaRZwGyQ4XqZx0tla1hm93ttFXkp1Idf1Nei0gKbnnOhRVzH8Vc4Uw9uoJqloCOVzhIVUlW0bZyLcnkruInZUuWLrxHPp5xgIFqHCmlkUTLghyER04Z2ibsuUbZVrF9Vo/wp4450TqB0+zXOM4jIybvMt96rgk+02jx9e8HkW4MHt1g0vscVfOCdOvBq92h8kYOZQY/+gHfTRZ+YrO+fzTi6TOV1N4ScgJaMjZo3RZ7c9ig2TPGzRXPXmXslUkZkyFt0zzb6Z+fM/QVngxAQej/PqlACCT9QOmnRilMB7r8JxX35Km6ocK8Tb6xbMYbhKnGLp30cl3AdpIEl7UcVthyX9uV/R6uiebI55d2nZsR6U5LkyCo59ENuPHqcRs708vocL2qm+PxCv11NV+aVaniIJsI37ToyKg7vwf26OqaKY23RBU6r/SV9MNjmab+aJH8bSSRlRw9q7tGjLDxjniLHPEFiHd6/slgoOEJ3lVYFkzF1fJ+SSe6f2QNXotyRXBK0fN39oUSaQTDQfj7tE/Jt3NFSlBXKy9fNjdpQ9QNyWkp+Q5X4EEc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
